services:
  postgres:
    image: postgres:15-alpine
    container_name: library-return-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library_return
      TZ: Asia/Kuala_Lumpur
    ports:
      - "5432:5432"
    volumes:
      - lib_postgres_data:/var/lib/postgresql/data
      - ../sql/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ../sql/seeds/seed_data.sql:/docker-entrypoint-initdb.d/02-seed_data.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - library-return-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: library-return-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@library.edu
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "5050:80"
    volumes:
      - lib_pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - library-return-network

volumes:
  lib_postgres_data:
    driver: local
  lib_pgadmin_data:
    driver: local

networks:
  library-return-network:
    driver: bridge
